"""Схемы запросов и ответов API.

Модули разделены по сущностям контракта (`05_API.md` §1): общие enum, ошибки, сценарий,
проекты и варианты, запуски, результаты, эксперименты. Пакет реэкспортирует их, чтобы
роутеры и тесты импортировали схемы из одного места.
"""

from orbita_api.schemas.common import (
    EdgeKind,
    OutageCause,
    ParameterChange,
    ParameterValue,
    RoutingPolicy,
    RunStage,
    RunStatus,
    SiteRole,
)
from orbita_api.schemas.errors import (
    NOT_FOUND_CODE,
    NOT_IMPLEMENTED_CODE,
    ErrorCode,
    ErrorDetail,
    ErrorResponse,
    ValidationErrorResponse,
    error_responses,
)
from orbita_api.schemas.experiments import (
    Experiment,
    ExperimentAxis,
    ExperimentBudget,
    ExperimentCreateRequest,
    ExperimentPoint,
    PointMaterializeRequest,
)
from orbita_api.schemas.projects import (
    TITLE_MAX_LENGTH,
    LineageEdge,
    LineageGraph,
    LineageNode,
    Project,
    ProjectCreateRequest,
    ProjectDetail,
    Variant,
    VariantCreateRequest,
)
from orbita_api.schemas.results import (
    RESULT_SCHEMA_VERSION,
    ClientDelta,
    ClientMetrics,
    ComparisonEntry,
    ComparisonRequest,
    ComparisonResult,
    ConfigMetrics,
    CriticalityReport,
    CriticalityRequest,
    OutageInterval,
    Recommendation,
    RouteRecord,
    RunExport,
    RunMetrics,
    SatelliteCriticality,
)
from orbita_api.schemas.runs import (
    BackupPaths,
    ClientRoute,
    ClientTimeline,
    PreviewRequest,
    Run,
    RunCreateRequest,
    RunProgressEvent,
    RunTimeline,
    Snapshot,
    SnapshotEdge,
    SnapshotSatellite,
)
from orbita_api.schemas.scenario import (
    SCENARIO_SCHEMA_VERSION,
    Design,
    Environment,
    GatewayOutage,
    GroundSite,
    Plane,
    Satellite,
    SatelliteFailure,
    Scenario,
    ScenarioMeta,
    ScenarioValidationResult,
)
from orbita_api.schemas.service import (
    HealthResponse,
    ServiceName,
    ServiceStatus,
    VersionResponse,
)

__all__ = [
    "NOT_FOUND_CODE",
    "NOT_IMPLEMENTED_CODE",
    "RESULT_SCHEMA_VERSION",
    "SCENARIO_SCHEMA_VERSION",
    "TITLE_MAX_LENGTH",
    "BackupPaths",
    "ClientDelta",
    "ClientMetrics",
    "ClientRoute",
    "ClientTimeline",
    "ComparisonEntry",
    "ComparisonRequest",
    "ComparisonResult",
    "ConfigMetrics",
    "CriticalityReport",
    "CriticalityRequest",
    "Design",
    "EdgeKind",
    "Environment",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "Experiment",
    "ExperimentAxis",
    "ExperimentBudget",
    "ExperimentCreateRequest",
    "ExperimentPoint",
    "GatewayOutage",
    "GroundSite",
    "HealthResponse",
    "LineageEdge",
    "LineageGraph",
    "LineageNode",
    "OutageCause",
    "OutageInterval",
    "ParameterChange",
    "ParameterValue",
    "Plane",
    "PointMaterializeRequest",
    "PreviewRequest",
    "Project",
    "ProjectCreateRequest",
    "ProjectDetail",
    "Recommendation",
    "RouteRecord",
    "RoutingPolicy",
    "Run",
    "RunCreateRequest",
    "RunExport",
    "RunMetrics",
    "RunProgressEvent",
    "RunStage",
    "RunStatus",
    "RunTimeline",
    "Satellite",
    "SatelliteCriticality",
    "SatelliteFailure",
    "Scenario",
    "ScenarioMeta",
    "ScenarioValidationResult",
    "ServiceName",
    "ServiceStatus",
    "SiteRole",
    "Snapshot",
    "SnapshotEdge",
    "SnapshotSatellite",
    "ValidationErrorResponse",
    "Variant",
    "VariantCreateRequest",
    "VersionResponse",
    "error_responses",
]
